In [1]:
import numpy as np
import pandas as pd

In [2]:
file = "instanca2.txt"

In [3]:
with open(file, "r") as infile:
    nj = infile.readlines()

In [4]:
nj

['53\n',
 '29\n',
 '\n',
 '42 42 42 44 44 53 53 53 53 53 53 42 53 53 53 42 53 53 53 42 53 53 42 53 53 42 42 53 42 42 42 44 42 53 42 44 53 42 53 42 42 42 42 42 42 42 42 42 42 53 42 53 42 \n',
 '\n',
 '2 2 2 3 3 1 1 1 1 1 1 2 1 1 1 2 1 1 1 2 1 1 2 1 1 2 2 1 2 2 2 3 2 1 2 3 1 2 1 2 2 2 2 2 2 2 2 2 2 1 2 1 2 \n',
 '\n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 \n',
 '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [24]:
lj = []
for i in nj[:]:
    lj.append(i.split())

In [6]:
broj_vozila = int(lj[0][0])
broj_traka = int(lj[1][0])

print(broj_vozila)
print(broj_traka)

53
29


In [7]:
duljina_vozila = np.array(lj[3], dtype = int)
duljina_vozila

array([42, 42, 42, 44, 44, 53, 53, 53, 53, 53, 53, 42, 53, 53, 53, 42, 53,
       53, 53, 42, 53, 53, 42, 53, 53, 42, 42, 53, 42, 42, 42, 44, 42, 53,
       42, 44, 53, 42, 53, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 53, 42,
       53, 42])

In [8]:
serija_vozila = np.array(lj[5], dtype = int)
serija_vozila

array([2, 2, 2, 3, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       2, 1, 1, 2, 2, 1, 2, 2, 2, 3, 2, 1, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 2])

In [9]:
ogranicenja_trake = np.array(lj[7:7+broj_vozila], dtype = int)
ogranicenja_trake

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [10]:
ogranicenja_trake.shape

(53, 29)

In [11]:
assert ogranicenja_trake.shape[0] == broj_vozila
assert ogranicenja_trake.shape[1] == broj_traka

In [12]:
duljina_trake =  np.array(lj[7+broj_vozila+1], dtype = int)
duljina_trake

array([ 74,  83,  90,  97,  96, 133, 132, 132, 134, 134, 134, 128,  85,
        88, 124, 120, 124, 107, 107, 107, 107,  91,  88,  85,  78,  88,
        70,  66,  80])

In [13]:
vrijeme_izlaska = np.array(lj[7+broj_vozila+3], dtype = int)
vrijeme_izlaska

array([345, 360, 375, 378, 395, 405, 406, 409, 425, 437, 381, 419, 254,
       256, 261, 307, 314, 324, 334, 344, 389, 397, 402, 410, 429, 433,
       442, 278, 283, 288, 293, 298, 303, 313, 318, 323, 333, 341, 351,
       383, 393, 434, 308, 312, 322, 332, 342, 438, 396, 274, 380, 392,
       264])

In [16]:
tip_rasporeda = np.array(lj[7+broj_vozila+5], dtype = int)
tip_rasporeda

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 4, 6, 6, 6, 6])

In [17]:
ograničenja = lj[7+broj_vozila+5+2:]
ograničenja

[['5', '4'],
 ['8', '7'],
 ['12', '13', '14'],
 ['21', '22'],
 ['23', '22'],
 ['25', '24'],
 ['28', '27', '29']]

In [19]:
vozilo = {}

for key1 in range(0, 53):
    # jer id od 1 ide..
    vozilo[key1+1] = {"duljina": duljina_vozila[key1], "serija": serija_vozila[key1], "izlazak": vrijeme_izlaska[key1], "raspored":tip_rasporeda[key1]}

In [20]:
vozilo

{1: {'duljina': 42, 'serija': 2, 'izlazak': 345, 'raspored': 6},
 2: {'duljina': 42, 'serija': 2, 'izlazak': 360, 'raspored': 6},
 3: {'duljina': 42, 'serija': 2, 'izlazak': 375, 'raspored': 6},
 4: {'duljina': 44, 'serija': 3, 'izlazak': 378, 'raspored': 6},
 5: {'duljina': 44, 'serija': 3, 'izlazak': 395, 'raspored': 6},
 6: {'duljina': 53, 'serija': 1, 'izlazak': 405, 'raspored': 6},
 7: {'duljina': 53, 'serija': 1, 'izlazak': 406, 'raspored': 6},
 8: {'duljina': 53, 'serija': 1, 'izlazak': 409, 'raspored': 6},
 9: {'duljina': 53, 'serija': 1, 'izlazak': 425, 'raspored': 6},
 10: {'duljina': 53, 'serija': 1, 'izlazak': 437, 'raspored': 6},
 11: {'duljina': 53, 'serija': 1, 'izlazak': 381, 'raspored': 1},
 12: {'duljina': 42, 'serija': 2, 'izlazak': 419, 'raspored': 1},
 13: {'duljina': 53, 'serija': 1, 'izlazak': 254, 'raspored': 6},
 14: {'duljina': 53, 'serija': 1, 'izlazak': 256, 'raspored': 6},
 15: {'duljina': 53, 'serija': 1, 'izlazak': 261, 'raspored': 6},
 16: {'duljina': 42

In [27]:
vozilo[1]["serija"]

2

In [30]:
vozilo[53]["izlazak"]

264

In [31]:
sorted_by_izlazak = sorted(vozilo.items(), key=lambda kv: kv[1]["izlazak"])
sorted_by_izlazak

[(13, {'duljina': 53, 'serija': 1, 'izlazak': 254, 'raspored': 6}),
 (14, {'duljina': 53, 'serija': 1, 'izlazak': 256, 'raspored': 6}),
 (15, {'duljina': 53, 'serija': 1, 'izlazak': 261, 'raspored': 6}),
 (53, {'duljina': 42, 'serija': 2, 'izlazak': 264, 'raspored': 6}),
 (50, {'duljina': 53, 'serija': 1, 'izlazak': 274, 'raspored': 6}),
 (28, {'duljina': 53, 'serija': 1, 'izlazak': 278, 'raspored': 0}),
 (29, {'duljina': 42, 'serija': 2, 'izlazak': 283, 'raspored': 0}),
 (30, {'duljina': 42, 'serija': 2, 'izlazak': 288, 'raspored': 0}),
 (31, {'duljina': 42, 'serija': 2, 'izlazak': 293, 'raspored': 0}),
 (32, {'duljina': 44, 'serija': 3, 'izlazak': 298, 'raspored': 0}),
 (33, {'duljina': 42, 'serija': 2, 'izlazak': 303, 'raspored': 0}),
 (16, {'duljina': 42, 'serija': 2, 'izlazak': 307, 'raspored': 6}),
 (43, {'duljina': 42, 'serija': 2, 'izlazak': 308, 'raspored': 1}),
 (44, {'duljina': 42, 'serija': 2, 'izlazak': 312, 'raspored': 0}),
 (34, {'duljina': 53, 'serija': 1, 'izlazak': 31

In [42]:
# id vozila sortirani po vremenu izlaska

np.array(sorted_by_value)[:,0]

array([13, 14, 15, 53, 50, 28, 29, 30, 31, 32, 33, 16, 43, 44, 34, 17, 35,
       45, 36, 18, 46, 37, 19, 38, 47, 20, 1, 39, 2, 3, 4, 51, 11, 40, 21,
       52, 41, 5, 49, 22, 23, 6, 7, 8, 24, 12, 9, 25, 26, 42, 10, 48, 27],
      dtype=object)